### ISSUE TITLE
Send Raw Transaction Not Sending

### ISSUE THREAD

**Issue by JB395** [qtumproject/qtuminfo#13]
qtum.info – MISC – SEND RAW TRANSACTION is not sending signed transactions to the network. 

Entering correct raw signed transactions and pressing the “Submit” button produces no response and does not send the transaction. If the transaction is corrupted, error messages appear. 

Using Chrome/Win 10 on Testnet, signed raw transactions composed in the Core wallet and the Web Wallet (Safe Send) are not sent to the network with qtum.info, but are sent properly with testnet.qtum.org/ Send Raw Transaction, which responds with a success message and the TX ID.

**Comment by xuanyan0x7c7** [comment]
Fixed
