### ISSUE TITLE
syntax errors preventing 'npm start' in packages/explorer directory from completing

### ISSUE THREAD

**Issue by denuoweb** [qtumproject/qtuminfo#14]
You can see the errors on github, they are highlighted red.     

```
let value = (BigInt(high) << 32n) + BigInt(low)
                             ^^
SyntaxError: Invalid or unexpected token
```

- github.com/qtumproject/qtuminfo/blob/master/packages/qtuminfo-lib/lib/encoding/base58.mjs

- github.com/qtumproject/qtuminfo/blob/master/packages/qtuminfo-lib/lib/encoding/buffer-reader.mjs

- github.com/qtumproject/qtuminfo/blob/master/packages/qtuminfo-lib/lib/encoding/buffer-writer.mjs

- github.com/qtumproject/qtuminfo/blob/master/packages/qtuminfo-lib/lib/transaction/output.mjs

**Comment by xuanyan0x7c7** [comment]
Please use nodejs v10.5 or later
