### ISSUE TITLE
有个疑问

### ISSUE THREAD

**Issue by chenzhuo112** [qtumproject/qtuminfo#22]
如何获取genesis: Buffer.from，钱包命令并不让获取genesis的Hex。应该获取哪个区块高度的genesis: Buffer.from？

**Comment by xuanyan0x7c7** [comment]
You may get raw genesis block in two steps:
1. `qtum-cli getblockhash 0` to get genesis block hash.
2. `qtum-cli getblock <hash> 0` to get raw genesis block data.

**Comment by chenzhuo112** [comment]
谢谢，为何我从头开始学习部署获取的genesis: Buffer.from（...................，hex）没有本来的长度，好像短了一大截，导致会出现 ‘Transaction Service: UniqueConstraintError [SequelizeUniqueConstraintError]: Validation error’的错误

**Comment by xuanyan0x7c7** [comment]
可能数据库清空一下就好了

**Comment by chenzhuo112** [comment]
我怎么没想到呢😂，脑子没转过来
